<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>TeethInc.Chantry</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyVersion>1.0.0</AssemblyVersion>
	<AssemblyFileVersion>0.2</AssemblyFileVersion>
    <FileVersion>1.0.0</FileVersion>
    <AssemblyName>Platescape</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.10" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.0.10" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.10" />
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.0.0.18" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.10.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
   </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chantry.Core\Chantry.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\Panels\FiltersView.axaml.cs">
      <DependentUpon>FiltersView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Panels\MosaicPropertiesView.axaml.cs">
      <DependentUpon>MosaicPropertiesView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Tabs\SourceView.axaml.cs">
      <DependentUpon>SourceView.axaml</DependentUpon>
    </Compile>
    <Compile Update="UserControls\MosaicViewer.axaml.cs">
      <DependentUpon>MosaicViewer.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\app.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Export\ViewModels\" />
    <Folder Include="Export\Views\" />
  </ItemGroup>
</Project>
