<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>TeethInc.Chantry.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.10.10" />
    <PackageReference Include="Avalonia.Desktop" Version="0.10.10" />
    <PackageReference Include="Avalonia.Diagnostics" Version="0.10.10" />
    <PackageReference Include="runtime.osx.10.10-x64.CoreCompat.System.Drawing" Version="6.0.5.128" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
   </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chantry.Core\Chantry.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="PropertyPages\ProjectPage.axaml.cs">
      <DependentUpon>ProjectPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Pages\FilteredImagePage.axaml.cs">
      <DependentUpon>FilteredImagePage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Pages\UnfilteredImagePage.axaml.cs">
      <DependentUpon>UnfilteredImagePage.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\*" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="SplashView.axaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="SplashView.axaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\splash.jpg" />
  </ItemGroup>
</Project>
