<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>TeethInc.Chantry</RootNamespace>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyVersion>2022.12</AssemblyVersion>
	<AssemblyFileVersion>2022.12</AssemblyFileVersion>
    <FileVersion>2022.12</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.6" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.0.6" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.0.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.6" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
   </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chantry.Core\Chantry.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="PropertyPages\MosaicProperties.axaml.cs">
      <DependentUpon>MosaicProperties.axaml</DependentUpon>
    </Compile>
    <Compile Update="PropertyPages\ProjectPage.axaml.cs">
      <DependentUpon>ProjectPage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Pages\FilteredImagePage.axaml.cs">
      <DependentUpon>FilteredImagePage.axaml</DependentUpon>
    </Compile>
    <Compile Update="Pages\UnfilteredImagePage.axaml.cs">
      <DependentUpon>UnfilteredImagePage.axaml</DependentUpon>
    </Compile>
    <Compile Update="UserControls\MosaicViewer.axaml.cs">
      <DependentUpon>MosaicViewer.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\*" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Remove="Assets\brightness.svg" />
    <AvaloniaResource Remove="Assets\contrast.svg" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaXaml Remove="SplashView.axaml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="SplashView.axaml.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\brightness.svg" />
    <None Remove="Assets\contrast.svg" />
    <None Remove="Assets\splash.jpg" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\app.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <UpToDateCheckInput Remove="UserControls\ExportSettingsControl.axaml" />
  </ItemGroup>
</Project>
