name: Publish Chantry

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x

    - name: Build win-x64
      run: dotnet publish src/Chantry/Chantry.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishTrimmed=true --self-contained true --output publish

    - name: Build osx-x64
      run: dotnet publish src/Chantry/Chantry.csproj -c Release -r osx-x64 -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishTrimmed=true --self-contained true --output publish
      
    - name: Upload win-x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: platescape-win-x64
        path: publish/Platescape.exe

    - name: Upload osx-x64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: platescape-osx-x64
        path: publish/Platescape
